# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AskAway' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'SideMenu'
  pod 'SwiftOverlays', '~> 4.0.0'
  pod 'DGElasticPullToRefresh' , :git => 'https://github.com/sammygutierrez/DGElasticPullToRefresh'
  pod 'XLPagerTabStrip'
  pod 'SwiftyShadow', '~> 1.6.0'
  pod 'PopupDialog', '~> 0.7'
  pod 'JSQMessagesViewController'
  # Pods for AskAway

end
