# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AskAway' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'SideMenu'
  #pod 'FirebaseUI'
  pod 'DGElasticPullToRefresh' , :git => 'https://github.com/sammygutierrez/DGElasticPullToRefresh'
  #pod 'FoldingCell'






  # Pods for AskAway

end
